apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qrserve-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # Set true if configuring SSL certificates
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx # Ensures mapping to your active Nginx controller deployment
  rules:
  - host: api.qrserve.local # Replace with your destination testing domain name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port: 
              number: 8081
